Feature/93 azure pipelines cd
fundev3/teamup-projects pull request #11
Opened 2021-07-22 20:11 UTC by alejandro-castellon-jalafund

AB#93

2021-07-22 20:22 UTC, pedro-lima-jalafund commented
please follow [this](https://github.com/fundev3/teamup-webapp/blob/develop/.github/PULL_REQUEST_TEMPLATE.md) for the description of this PR

2021-07-22 22:58 UTC, martin-callejas-jalafund requested changes
Minor obs! Awesome job

2021-07-22 22:58 UTC, martin-callejas-jalafund commented on azure-pipelines.yml
> +  displayName: Build stage
just `Build`

2021-07-22 22:58 UTC, martin-callejas-jalafund commented on azure-pipelines.yml
> +      displayName: 'Dotnet Build'
DotNet

2021-07-22 22:58 UTC, martin-callejas-jalafund commented on azure-pipelines.yml
> +    - task: ArchiveFiles@2
displayName: 'Archive files'

2021-07-22 22:58 UTC, martin-callejas-jalafund commented on azure-pipelines.yml
> +      displayName: 'Dotnet Drop Artifacts'
Drop Artifact

2021-07-22 22:58 UTC, martin-callejas-jalafund commented on azure-pipelines.yml
> +  displayName: Deploy stage
just Deploy

2021-07-22 23:11 UTC, martin-callejas-jalafund submitted a review, later dismissed
get your other two students approvals and we're good to merge

2021-07-23 00:14 UTC, martin-callejas-jalafund requested changes

2021-07-23 00:14 UTC, martin-callejas-jalafund commented on azure-pipelines.yml
> +      vmImage: 'ubuntu-latest'
let's remove pool here, we only need it at pipeline level https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#pool

2021-07-23 00:14 UTC, martin-callejas-jalafund commented on azure-pipelines.yml
> +    - task: DownloadBuildArtifacts@1
add displayName: Download Artifact

2021-07-23 00:14 UTC, martin-callejas-jalafund commented on azure-pipelines.yml
> +    - task: AzureFunctionApp@1
add displayName: Deploy API

2021-07-23 00:34 UTC, fernando-maceda-fundacion approved these changes, later dismissed
LGTM

2021-07-23 00:38 UTC, paulo-teran-jalafund submitted a review, later dismissed
LGTM

2021-07-23 00:39 UTC, pedro-lima-jalafund submitted a review, later dismissed

2021-07-23 00:40 UTC, martin-callejas-jalafund requested changes

2021-07-23 00:40 UTC, martin-callejas-jalafund commented on azure-pipelines.yml
> +      vmImage: ubuntu-latest
move to pipeline level

2021-07-23 00:47 UTC, martin-callejas-jalafund approved these changes

2021-07-23 00:47 UTC, pedro-lima-jalafund approved these changes

2021-07-23 00:50 UTC, paulo-teran-jalafund approved these changes

2021-07-23 00:50 UTC, rodrigo-baldiviezo-jalafund approved these changes

2021-07-23 00:54 UTC, merged